name: deloy test

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ubuntu container
        run: |
          docker run --rm ubuntu:latest bash -c "echo Hello from Ubuntu container on CentOS!"
      - name: Build & Deploy
        env:
          HOSTNAME: ${{secrets.ECS_IP}}
          USER_NAME: ${{secrets.ECS_USER}}
          PRIVATE_KEY: ${{secrets.ECS_RSA}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ~/fishAI;
            echo '------ cd done ------' ;
            git checkout test-deploy
            git checkout .
            git pull origin test-deploy
            echo '------ git pull done ------' ;
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=fishai-web-docker))
            echo '------ docker rm done ------' ;
            docker build -t fishai-web-docker .
            echo '------ docker build done ------'
            docker run -d -p 3001:3000 fishai-web-docker
            echo '------ docker run done ------' ;
          '
      - name: success
        run: echo "deploy success"
