name: Deploy fishAI Web (staging)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ 这里恢复你原来在服务器的 .npmrc 注入逻辑
      - name: Inject .npmrc
        run: |
          echo "${{secrets.NPMRC_FOR_TEST}}" > .npmrc
          echo "✅ Created .npmrc for private registry"

      # ✅ 可选：打印确认（但不显示敏感内容）
      - name: Verify .npmrc
        run: head -n 3 .npmrc || true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t fishai-web:staging .

      - name: Save and send image to server
        env:
          HOST: ${{ secrets.ECS_IP }}
          USER: ${{ secrets.ECS_USER }}
          SSH_KEY: ${{ secrets.ECS_RSA }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          docker save fishai-web:staging | bzip2 | \
            ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} \
            "bunzip2 | docker load"

      - name: Restart container remotely
        env:
          HOST: ${{ secrets.ECS_IP }}
          USER: ${{ secrets.ECS_USER }}
          SSH_KEY: ${{ secrets.ECS_RSA }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            docker compose -f /root/docker-compose.staging.yml up -d fishai-web
          '

      - name: Success
        run: echo "✅ fishAI (Next.js) deployed successfully!"
